### ISSUE TITLE
Demos don't work

### ISSUE THREAD

**Issue by mogarg** [belaban/jgroups-raft#49]
> Exception in thread "main" java.lang.NullPointerException
> 	at org.jgroups.protocols.raft.RAFT.createLogName(RAFT.java:955)
> 	at org.jgroups.protocols.raft.RAFT.start(RAFT.java:430)
> 	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:965)
> 	at org.jgroups.JChannel.startStack(JChannel.java:890)
> 	at org.jgroups.JChannel._preConnect(JChannel.java:553)
> 	at org.jgroups.JChannel.connect(JChannel.java:288)
> 	at org.jgroups.JChannel.connect(JChannel.java:279)
> 	at org.jgroups.raft.demos.ReplicatedStateMachineDemo.start(ReplicatedStateMachineDemo.java:30)
> 	at org.jgroups.raft.demos.ReplicatedStateMachineDemo.main(ReplicatedStateMachineDemo.java:184)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by belaban** [comment]
The reason for the NPE was that you did not define `raft_id`, e.g. 
`java org.jgroups.raft.demos.ReplicatedStateMachineDemo -name A`. I fixed this; now if you don't define raft_id, the following exception will be thrown:

{noformat}
Exception in thread "main" java.lang.IllegalStateException: raft-id undefined is not listed in members [A, B, C]
	at org.jgroups.protocols.raft.RAFT.start(RAFT.java:442)
	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:966)
	at org.jgroups.JChannel.startStack(JChannel.java:889)
	at org.jgroups.JChannel._preConnect(JChannel.java:553)
	at org.jgroups.JChannel.connect(JChannel.java:288)
	at org.jgroups.JChannel.connect(JChannel.java:279)
	at org.jgroups.raft.demos.ReplicatedStateMachineDemo.start(ReplicatedStateMachineDemo.java:30)
	at org.jgroups.raft.demos.ReplicatedStateMachineDemo.main(ReplicatedStateMachineDemo.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
{noformat}
